export const CUSTOMER_ADD_REQUEST = "CUSTOMER_ADD_REQUEST";
export const CUSTOMER_ADD_SUCCESS = "CUSTOMER_ADD_SUCCESS";
export const CUSTOMER_ADD_FAIL = "CUSTOMER_ADD_FAIL";
export const CUSTOMER_ADD_CLEAR = "CUSTOMER_ADD_CLEAR";

export const CUSTOMERS_REQUEST = "CUSTOMERS_REQUEST";
export const CUSTOMERS_SUCCESS = "CUSTOMERS_SUCCESS";
export const CUSTOMERS_FAIL = "CUSTOMERS_FAIL";
export const CUSTOMERS_CLEAR = "CUSTOMERS_CLEAR";

export const CUSTOMER_UPDATE_REQUEST = "CUSTOMER_UPDATE_REQUEST";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAIL = "CUSTOMER_UPDATE_FAIL";
export const CUSTOMER_UPDATE_CLEAR = "CUSTOMER_UPDATE_CLEAR";