export const FARM_ANIMALS_REQUEST = "FARM_ANIMALS_REQUEST";
export const FARM_ANIMALS_SUCCESS = "FARM_ANIMALS_SUCCESS";
export const FARM_ANIMALS_FAIL = "FARM_ANIMALS_FAIL";

export const FARM_ANIMAL_ADD_REQUEST = "FARM_ANIMAL_ADD_REQUEST";
export const FARM_ANIMAL_ADD_SUCCESS = "FARM_ANIMAL_ADD_SUCCESS";
export const FARM_ANIMAL_ADD_FAIL = "FARM_ANIMAL_ADD_FAIL";