export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_UPDATENAME_REQUEST = "USER_UPDATENAME_REQUEST";
export const USER_UPDATENAME_SUCCESS = "USER_UPDATENAME_SUCCESS";
export const USER_UPDATENAME_FAIL = "USER_UPDATENAME_FAIL";

export const USER_UPDATEPASSWORD_REQUEST = "USER_UPDATEPASSWORD_REQUEST";
export const USER_UPDATEPASSWORD_SUCCESS = "USER_UPDATEPASSWORD_SUCCESS";
export const USER_UPDATEPASSWORD_FAIL = "USER_UPDATEPASSWORD_FAIL";