export const WORKER_UPDATENAME_REQUEST = "WORKER_UPDATENAME_REQUEST";
export const WORKER_UPDATENAME_SUCCESS = "WORKER_UPDATENAME_SUCCESS";
export const WORKER_UPDATENAME_FAIL = "WORKER_UPDATENAME_FAIL";

export const WORKER_UPDATENUMBER_REQUEST = "WORKER_UPDATENUMBER_REQUEST";
export const WORKER_UPDATENUMBER_SUCCESS = "WORKER_UPDATENUMBER_SUCCESS";
export const WORKER_UPDATENUMBER_FAIL = "WORKER_UPDATENUMBER_FAIL";

export const WORKER_UPDATEWORK_REQUEST = "WORKER_UPDATEWORK_REQUEST";
export const WORKER_UPDATEWORK_SUCCESS = "WORKER_UPDATEWORK_SUCCESS";
export const WORKER_UPDATEWORK_FAIL = "WORKER_UPDATEWORK_FAIL";

export const WORKER_UPDATECNIC_REQUEST = "WORKER_UPDATECNIC_REQUEST";
export const WORKER_UPDATECNIC_SUCCESS = "WORKER_UPDATECNIC_SUCCESS";
export const WORKER_UPDATECNIC_FAIL = "WORKER_UPDATECNIC_FAIL";

export const WORKER_UPDATESTATUS_REQUEST = "WORKER_UPDATESTATUS_REQUEST";
export const WORKER_UPDATESTATUS_SUCCESS = "WORKER_UPDATESTATUS_SUCCESS";
export const WORKER_UPDATESTATUS_FAIL = "WORKER_UPDATESTATUS_FAIL";