export const FARM_ANIMALS_REQUEST = "FARM_ANIMALS_REQUEST";
export const FARM_ANIMALS_SUCCESS = "FARM_ANIMALS_SUCCESS";
export const FARM_ANIMALS_FAIL = "FARM_ANIMALS_FAIL";

export const FARM_ANIMAL_ADD_REQUEST = "FARM_ANIMAL_ADD_REQUEST";
export const FARM_ANIMAL_ADD_SUCCESS = "FARM_ANIMAL_ADD_SUCCESS";
export const FARM_ANIMAL_ADD_FAIL = "FARM_ANIMAL_ADD_FAIL";
export const FARM_ANIMAL_ADD_CLEAR = "FARM_ANIMAL_ADD_CLEAR";

export const FARM_ANIMAL_UPDATE_REQUEST = "FARM_ANIMAL_UPDATE_REQUEST";
export const FARM_ANIMAL_UPDATE_SUCCESS = "FARM_ANIMAL_UPDATE_SUCCESS";
export const FARM_ANIMAL_UPDATE_FAIL = "FARM_ANIMAL_UPDATE_FAIL";
export const FARM_ANIMAL_UPDATE_CLEAR = "FARM_ANIMAL_UPDATE_CLEAR";

export const FARM_MEMBERS_REQUEST = "FARM_MEMBERS_REQUEST";
export const FARM_MEMBERS_SUCCESS = "FARM_MEMBERS_SUCCESS";
export const FARM_MEMBERS_FAIL = "FARM_MEMBERS_FAIL";

export const FARM_WORKERS_REQUEST = "FARM_WORKERS_REQUEST";
export const FARM_WORKERS_SUCCESS = "FARM_WORKERS_SUCCESS";
export const FARM_WORKERS_FAIL = "FARM_WORKERS_FAIL";

export const FARM_INVENTORY_REQUEST = "FARM_INVENTORY_REQUEST";
export const FARM_INVENTORY_SUCCESS = "FARM_INVENTORY_SUCCESS";
export const FARM_INVENTORY_FAIL = "FARM_INVENTORY_FAIL";
